---
type: ClientRegistrySettings
fields:
  name: Client Registry Settings
children:
- type: Cookie
  fields:
    cookieName: CLIENTREGISTRYCOOKIE
    cookiePath: /
    cookieMaxAge: 3600
    cookieExpires: 3600
    cookieSecure: true
    cookieHttpOnly: true
